api = "0.7"

[buildpack]
  id = "paketo-buildpacks/pip"
  name = "Paketo Buildpack for Pip"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pip/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    checksum = "sha256:85d475907d2501c6a0b4ffcc173fd379a7a476e003d1c5e27d6fb8907933c4e3"
    cpe = "cpe:2.3:a:pypa:pip:26.2.0:*:*:*:*:python:*:*"
    id = "pip"
    licenses = ["MIT"]
    purl = "pkg:generic/pip@26.2.0?checksum=2d8542afcc84cdd8e846c2b36b2861fad1da376dd98f8e7113e9108a3c331690&download_url=https://files.pythonhosted.org/packages/db/96/e6f8e9d9d7b9cc4457092712a7e919c3186aa2c2fa9ffed2c5d29cc947e8/pip-26.2.tar.gz"
    source = "https://files.pythonhosted.org/packages/db/96/e6f8e9d9d7b9cc4457092712a7e919c3186aa2c2fa9ffed2c5d29cc947e8/pip-26.2.tar.gz"
    source-checksum = "sha256:2d8542afcc84cdd8e846c2b36b2861fad1da376dd98f8e7113e9108a3c331690"
    stacks = ["*"]
    uri = "https://artifacts.paketo.io/pip/pip_26.2.0_noarch_85d47590.tgz"
    version = "26.2.0"

  [[metadata.dependencies]]
    checksum = "sha256:285b99aaa6b3d108283a6d746f02fa029700363d32a81885d13f7d62c845b694"
    cpe = "cpe:2.3:a:pypa:pip:26.2.1:*:*:*:*:python:*:*"
    id = "pip"
    licenses = ["MIT"]
    purl = "pkg:generic/pip@26.2.1?checksum=f6ad667e89a1fe78046c8f13232b247200f5258d7828f3f7883d660878e0813f&download_url=https://files.pythonhosted.org/packages/ae/15/4500e320e6b101ec3b719ae85b697d9940b6cda672bc555bd6016fc60c6f/pip-26.2.1.tar.gz"
    source = "https://files.pythonhosted.org/packages/ae/15/4500e320e6b101ec3b719ae85b697d9940b6cda672bc555bd6016fc60c6f/pip-26.2.1.tar.gz"
    source-checksum = "sha256:f6ad667e89a1fe78046c8f13232b247200f5258d7828f3f7883d660878e0813f"
    stacks = ["*"]
    uri = "https://artifacts.paketo.io/pip/pip_26.2.1_noarch_285b99aa.tgz"
    version = "26.2.1"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "pip"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
