api = "0.7"

[buildpack]
  id = "paketo-buildpacks/pip"
  name = "Paketo Buildpack for Pip"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pip/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    checksum = "sha256:2acda90f699eb084a67af9437620e5afe65d57aeb78c35115d97fdc88bf9dcf2"
    cpe = "cpe:2.3:a:pypa:pip:26.1.1:*:*:*:*:python:*:*"
    id = "pip"
    licenses = ["MIT"]
    purl = "pkg:generic/pip@26.1.1?checksum=d36762751d156a4ee895de8af39aa0abeeeb577f93a2eca6ab62467bbf0f8a78&download_url=https://files.pythonhosted.org/packages/b6/48/cb9b7a682f6fe01a4221e1728941dd4ac3cd9090a17db3779d6ff490b602/pip-26.1.1.tar.gz"
    source = "https://files.pythonhosted.org/packages/b6/48/cb9b7a682f6fe01a4221e1728941dd4ac3cd9090a17db3779d6ff490b602/pip-26.1.1.tar.gz"
    source-checksum = "sha256:d36762751d156a4ee895de8af39aa0abeeeb577f93a2eca6ab62467bbf0f8a78"
    stacks = ["*"]
    uri = "https://artifacts.paketo.io/pip/pip_26.1.1_noarch_2acda90f.tgz"
    version = "26.1.1"

  [[metadata.dependencies]]
    checksum = "sha256:1bed3b728c22d205f659b3ef7387e347131a9e8c14517d40ef31bce62888c06f"
    cpe = "cpe:2.3:a:pypa:pip:26.1.2:*:*:*:*:python:*:*"
    id = "pip"
    licenses = ["MIT"]
    purl = "pkg:generic/pip@26.1.2?checksum=f49cd134c61cf2fd75e0ce2676db03e4054504a5a4986d00f8299ae632dc4605&download_url=https://files.pythonhosted.org/packages/01/91/47e7d486260f618783899587af63ccf7980fb60245c3e63dd4571c6b57ad/pip-26.1.2.tar.gz"
    source = "https://files.pythonhosted.org/packages/01/91/47e7d486260f618783899587af63ccf7980fb60245c3e63dd4571c6b57ad/pip-26.1.2.tar.gz"
    source-checksum = "sha256:f49cd134c61cf2fd75e0ce2676db03e4054504a5a4986d00f8299ae632dc4605"
    stacks = ["*"]
    uri = "https://artifacts.paketo.io/pip/pip_26.1.2_noarch_1bed3b72.tgz"
    version = "26.1.2"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "pip"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
