api = "0.7"

[buildpack]
  id = "paketo-buildpacks/pip"
  name = "Paketo Buildpack for Pip"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pip/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    checksum = "sha256:33d061028c839cdea072ed398be0cf9105132b954ddb1fd02506f578e8832f20"
    cpe = "cpe:2.3:a:pypa:pip:26.0.1:*:*:*:*:python:*:*"
    id = "pip"
    licenses = ["MIT"]
    purl = "pkg:generic/pip@26.0.1?checksum=c4037d8a277c89b320abe636d59f91e6d0922d08a05b60e85e53b296613346d8&download_url=https://files.pythonhosted.org/packages/48/83/0d7d4e9efe3344b8e2fe25d93be44f64b65364d3c8d7bc6dc90198d5422e/pip-26.0.1.tar.gz"
    source = "https://files.pythonhosted.org/packages/48/83/0d7d4e9efe3344b8e2fe25d93be44f64b65364d3c8d7bc6dc90198d5422e/pip-26.0.1.tar.gz"
    source-checksum = "sha256:c4037d8a277c89b320abe636d59f91e6d0922d08a05b60e85e53b296613346d8"
    stacks = ["*"]
    uri = "https://artifacts.paketo.io/pip/pip_26.0.1_noarch_33d06102.tgz"
    version = "26.0.1"

  [[metadata.dependencies]]
    checksum = "sha256:ad744302d093b0a54b874d338cafa8c0ac81e4d75d8f570ad774f00683f357f3"
    cpe = "cpe:2.3:a:pypa:pip:26.1.0:*:*:*:*:python:*:*"
    id = "pip"
    licenses = ["MIT"]
    purl = "pkg:generic/pip@26.1.0?checksum=81e13ebcca3ffa8cc85e4deff5c27e1ee26dea0aa7fc2f294a073ac208806ff3&download_url=https://files.pythonhosted.org/packages/73/7e/d2b04004e1068ad4fdfa2f227b839b5d03e602e47cdbbf49de71137c9546/pip-26.1.tar.gz"
    source = "https://files.pythonhosted.org/packages/73/7e/d2b04004e1068ad4fdfa2f227b839b5d03e602e47cdbbf49de71137c9546/pip-26.1.tar.gz"
    source-checksum = "sha256:81e13ebcca3ffa8cc85e4deff5c27e1ee26dea0aa7fc2f294a073ac208806ff3"
    stacks = ["*"]
    uri = "https://artifacts.paketo.io/pip/pip_26.1.0_noarch_ad744302.tgz"
    version = "26.1.0"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "pip"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
